// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool},
		{Name: "is_student", Type: field.TypeBool},
		{Name: "is_teacher", Type: field.TypeBool},
		{Name: "created", Type: field.TypeTime},
		{Name: "phone", Type: field.TypeString, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
