// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the course type in the database.
	Label = "course"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldIsStudent holds the string denoting the is_student field in the database.
	FieldIsStudent = "is_student"
	// FieldIsTeacher holds the string denoting the is_teacher field in the database.
	FieldIsTeacher = "is_teacher"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// Table holds the table name of the course in the database.
	Table = "users"
)

// Columns holds all SQL columns for course fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhone,
	FieldPassword,
	FieldIsAdmin,
	FieldIsStudent,
	FieldIsTeacher,
	FieldCreated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultPhone holds the default value on creation for the "phone" field.
	DefaultPhone string
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultIsStudent holds the default value on creation for the "is_student" field.
	DefaultIsStudent bool
	// DefaultIsTeacher holds the default value on creation for the "is_teacher" field.
	DefaultIsTeacher bool
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
)
