// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"education/app/user/internal/biz"
	"education/app/user/internal/conf"
	"education/app/user/internal/data"
	"education/app/user/internal/server"
	"education/app/user/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, consul *conf.Consul, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepoInt := data.NewUserRepo(dataData, logger)
	userCase := biz.NewUserCase(userRepoInt, logger)
	userService := service.NewUserService(userCase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, userService, logger)
	registrar := server.NewConsulRegister(consul)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
